[project]
name = "excelipy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.10"
dependencies = [
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
    "xlsxwriter>=3.2.2",
]
